#!/usr/bin/env node
/**
 * Ringside Sports — Full Supplier Sync v3
 *
 * Reads the CLEANED XML (generated by legacy wc2_xml.py at 01:00 daily)
 * which has proper <product> wrappers with <variations>/<variation> children.
 *
 * Extracts ALL fields: variants, prices, stock, images, categories, tags
 * Handles: new products, removed products, attribute changes
 */
import { createHash } from "crypto";
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "fs";

const CLEANED_XML = "/home/ringsidesportsco/public_html/xml_clean/cleaned_product_inventory.xml";
const HASH_FILE = (process.env.SYNC_DATA_DIR || "/opt/ringsidesports/data") + "/sync-hash.txt";
const CATALOG_JSON = process.env.CATALOG_PATH || "/tmp/catalog-export.json";

function log(level, msg) { console.log(new Date().toISOString() + " [" + level + "] " + msg); }

// ── Category heuristic ─────────────────────────────────────────────────
const CAT_RULES = [
  { kw: ["BOXING GLOVES", "GLOVES", "HAYMAKER", "TROPHY GETTER", "TOUGH GUY", "FIGHT GLOVES", "CAGE CUTTER", "SPARRING"], cat: "Boxing Gloves" },
  { kw: ["MMA GLOVES", "MMA GLOVE"], cat: "MMA Gloves" },
  { kw: ["HAND WRAPS", "HANDWRAPS", "WRAPS", "QUICK WRAPS"], cat: "Hand Wraps" },
  { kw: ["HEAD GEAR", "HEADGEAR", "HEAD GUARD"], cat: "Protective Gear" },
  { kw: ["SHIN PADS", "SHIN GUARDS", "SHIN"], cat: "Protective Gear" },
  { kw: ["BODY PROTECTOR", "BODY GUARD", "CHEST GUARD", "BELLY PAD", "THIGH PAD", "GROIN GUARD", "ROUND SHIELD", "KNUCKLE PROTECTOR", "ANKLET"], cat: "Protective Gear" },
  { kw: ["MOUTHGUARD", "MOUTH GUARD", "GUM SHIELD"], cat: "Protective Gear" },
  { kw: ["BOXING BAG", "PUNCHING BAG", "HEAVY BAG", "SPEED BALL", "FREE STANDING", "UPPERCUT", "WALL BAG"], cat: "Punching & Training Bags" },
  { kw: ["PUNCH MITT", "FOCUS MITT", "HOOK JAB", "KICK SHIELD", "THAI PAD", "BAG MITT"], cat: "Punch Mitts & Pads" },
  { kw: ["SHORTS", "THAI SHORTS"], cat: "Martial Arts Shorts" },
  { kw: ["TSHIRT", "T-SHIRT", "HOODIE", "SINGLET", "RASH GUARD", "COMPRESSION", "MUSCLE SHIRT", "STEAMER SUIT", "CAP -"], cat: "Shirts & Tops" },
  { kw: ["BUNDLE", "STARTER PACK", "PRO STARTER", "PROMO PACK", "HOME GYM", "BONUS PACK", "PROTECTION PACK", "FITNESS PACK", "XMAS", "EDUCATION PACK"], cat: "Bundles" },
  { kw: ["DUFFEL", "GYM BAG", "BACKPACK", "GEAR BAG"], cat: "Gym Duffel Bags" },
  { kw: ["E-BOOK", "EBOOK", "PRINTED BOOK", "ONLINE"], cat: "E-Books" },
  { kw: ["GIFT CARD"], cat: "Gift Cards" },
  { kw: ["WEIGHT LIFTING", "LIFTING GLOVE", "HAND SUPPORT"], cat: "Weight Lifting Gloves & Supports" },
  { kw: ["FLOOR TO CEILING", "CHAIN", "SWIVEL"], cat: "Boxing & Martial Arts" },
  { kw: ["BOXING BOOT", "BOXING SHOE", "SLIP BALL", "BOXING GLOVE/ BOOT"], cat: "Boxing & Martial Arts" },
];

function deriveCategory(title) {
  const t = (title || "").toUpperCase();
  for (const r of CAT_RULES) if (r.kw.some(k => t.includes(k.toUpperCase()))) return r.cat;
  return "Boxing & Martial Arts";
}

// ── Parsing helpers ─────────────────────────────────────────────────────
function tag(block, name) {
  const m = block.match(new RegExp("<" + name + ">([^<]*)</" + name + ">"));
  return m ? m[1].trim() : "";
}

function stripHtml(html) {
  return (html || "").replace(/<[^>]*>/g, "").replace(/&amp;/g, "&").replace(/&lt;/g, "<").replace(/&gt;/g, ">").trim();
}

// ── Extract from cleaned XML ────────────────────────────────────────────
function extractAll() {
  log("INFO", "Reading cleaned XML...");
  if (!existsSync(CLEANED_XML)) throw new Error("Cleaned XML not found: " + CLEANED_XML);
  
  const xml = readFileSync(CLEANED_XML, "utf8");
  const hash = createHash("sha256").update(xml).digest("hex");
  
  const prevHash = existsSync(HASH_FILE) ? readFileSync(HASH_FILE, "utf8").trim() : null;
  if (prevHash === hash) { log("INFO", "Cleaned XML unchanged — skipping"); return null; }
  writeFileSync(HASH_FILE, hash);
  
  log("INFO", "Parsing products...");
  const products = [];
  const productRe = /<product>([\s\S]*?)<\/product>/g;
  let match;
  
  while ((match = productRe.exec(xml)) !== null) {
    const block = match[1];
    const supplierId = tag(block, "id");
    if (!supplierId) continue;
    
    const title = tag(block, "title") || "";
    const description = stripHtml(tag(block, "description"));
    const mpn = tag(block, "mpn") || tag(block, "sku") || "";
    const rawCat = tag(block, "category");
    const rawTags = tag(block, "tags");
    const productType = tag(block, "product_type") || "simple";
    
    // Images
    const images = [];
    const mainImg = tag(block, "image");
    if (mainImg) images.push(mainImg);
    const addImgs = [...block.matchAll(/<additional_image>([^<]+)<\/additional_image>/g)];
    addImgs.forEach(m => { if (m[1]) images.push(m[1]); });
    
    // Categories: from XML, with mapping
    let categories = [];
    if (rawCat && rawCat !== "Uncategorized") {
      categories = rawCat.replace(/&amp;/g, "&").replace(/&/g, ", ").split(",").map(s => s.trim()).filter(Boolean);
    }
    if (categories.length === 0) categories = [deriveCategory(title)];
    
    // Tags
    const tags = rawTags ? rawTags.split(",").map(s => s.trim()).filter(Boolean) : [];
    
    // Stock
    const stockRaw = tag(block, "stock_status") || "instock";
    const stockQty = parseInt(tag(block, "quantity") || "0", 10);
    
    // Variants from <variations><variation>
    const variants = [];
    const varRe = /<variation>([\s\S]*?)<\/variation>/g;
    let varMatch;
    while ((varMatch = varRe.exec(block)) !== null) {
      const vb = varMatch[1];
      const vid = tag(vb, "id") || "";
      const varTitle = tag(vb, "title") || title;
      const varPrice = parseFloat(tag(vb, "regular_price") || tag(vb, "price") || "0");
      const varSku = tag(vb, "sku") || mpn;
      const varStock = tag(vb, "stock_status") || "instock";
      const varQty = parseInt(tag(vb, "quantity") || tag(vb, "stock_quantity") || "0", 10);
      const size = tag(vb, "size") || "";
      const colour = tag(vb, "color") || tag(vb, "colour") || "";
      
      const options = {};
      if (size && size !== "Default Title") options.size = size;
      if (colour) options.colour = colour;
      
      const varImgs = [];
      const varImg = tag(vb, "image") || tag(vb, "variant_image");
      if (varImg) varImgs.push(varImg);
      
      const suppVariantSku = varSku.replace(/[^a-zA-Z0-9_.-]/g, "") || mpn + "_" + (size || "") + (colour ? "_" + colour : "");
      
      variants.push({
        supplierVariantSku: suppVariantSku,
        supplierIdentity: supplierId + "__" + suppVariantSku,
        sku: suppVariantSku,
        title: varTitle,
        price: Math.round(varPrice * 100),
        stockQuantity: varQty,
        stockStatus: varStock === "instock" ? "in_stock" : "out_of_stock",
        options,
        images: varImgs,
        wcVariationId: 0,
      });
    }
    
    // No variants? Create default
    if (variants.length === 0) {
      const defPrice = parseFloat(tag(block, "regular_price") || "0");
      variants.push({
        supplierVariantSku: mpn || "default",
        supplierIdentity: supplierId + "__" + (mpn || "default"),
        sku: mpn || "default",
        title,
        price: Math.round(defPrice * 100),
        stockQuantity: stockQty,
        stockStatus: stockRaw === "instock" ? "in_stock" : "out_of_stock",
        options: {}, images,
        wcVariationId: 0,
      });
    }
    
    const minPrice = Math.min(...variants.map(v => v.price));
    
    products.push({
      supplierId, id: supplierId,
      title, description,
      handle: title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "") + "-" + supplierId.slice(-8),
      status: "published",
      categories, tags, images, variants,
      productType: variants.length > 1 ? "variable" : "simple",
      price: minPrice,
      stockStatus: stockRaw === "instock" ? "in_stock" : "out_of_stock",
      stockQuantity: stockQty,
      supplierMpn: mpn,
      wcPostId: 0,
    });
  }
  
  const totalVars = products.reduce((s, p) => s + p.variants.length, 0);
  log("INFO", "Extracted " + products.length + " products, " + totalVars + " variants");
  return products;
}

// ── Merge with existing to preserve wcPostId ────────────────────────────
function mergeCatalog(newProducts) {
  log("INFO", "Merging with existing catalog...");
  
  let existing = { catalog: [] };
  try { existing = JSON.parse(readFileSync(CATALOG_JSON, "utf8")); } catch(e) {}
  
  const existingMap = new Map();
  for (const p of existing.catalog) existingMap.set(p.supplierId, p);
  
  const finalCatalog = [];
  let newCount = 0, updatedCount = 0;
  
  for (const np of newProducts) {
    const old = existingMap.get(np.supplierId);
    if (old) {
      np.wcPostId = old.wcPostId;
      // Preserve existing categories if cleaned XML has "Uncategorized" or empty
      if (np.categories.length === 0 || np.categories[0] === "Uncategorized") {
        if (old.categories.length > 0) np.categories = old.categories;
      }
      updatedCount++;
    } else {
      newCount++;
    }
    finalCatalog.push(np);
  }
  
  // Reconcile removed: mark outofstock
  const newIds = new Set(newProducts.map(p => p.supplierId));
  let removedCount = 0;
  for (const old of existing.catalog) {
    if (!newIds.has(old.supplierId)) {
      old.stockStatus = "out_of_stock";
      old.stockQuantity = 0;
      for (const v of old.variants) { v.stockStatus = "out_of_stock"; v.stockQuantity = 0; }
      finalCatalog.push(old);
      removedCount++;
    }
  }
  
  log("INFO", "New: " + newCount + " Updated: " + updatedCount + " Removed: " + removedCount);
  
  writeFileSync(CATALOG_JSON, JSON.stringify({ catalog: finalCatalog }, null, 2));
  log("INFO", "Saved: " + finalCatalog.length + " products total");
}

// ── Main ────────────────────────────────────────────────────────────────
function main() {
  mkdirSync((process.env.SYNC_DATA_DIR || "/opt/ringsidesports/data"), { recursive: true });
  const products = extractAll();
  if (!products) { log("INFO", "Done — no changes"); return; }
  mergeCatalog(products);
  log("INFO", "Full sync complete");
}
main();
